server:
  port: 8081
  error:
    include-message: always
#Configuracion de spring
spring:
  #Configuracion de migracion
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  datasource:
    url: jdbc:postgresql://bubble.db.elephantsql.com:5432/ctpwahxc?socketTimeout=3
    username: ctpwahxc
    password: aT0Z-UaiQOXbhoJtJU2OFlcHoIVDsi4e
    driverClassName: org.postgresql.Driver